project_id = "hvbdeyuqcliqrmzvyciq"

[functions.virtual-staging]
verify_jwt = false

[functions.get-huggingface-token]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = false

[functions.public-api]
verify_jwt = false

[functions.extract-property-data]
verify_jwt = true

[functions.feeds-cnm]
verify_jwt = false

[functions.feeds-olx]
verify_jwt = false