project_id = "paawojkqrggnuvpnnwrc"

[functions.asaas-integration]
verify_jwt = false

[functions.sync-asaas-payments]
verify_jwt = false

[functions.create-public-subscription]
verify_jwt = false

[functions.create-asaas-checkout-link]
verify_jwt = false

[functions.claim-subscription]
verify_jwt = true

[functions.send-signup-email]
verify_jwt = false

[functions.minisite-ai-chat]
verify_jwt = false

[functions.conecta-ai-chat]
verify_jwt = false

[functions.virtual-staging]
verify_jwt = false

[functions.private-api]
verify_jwt = false

[functions.get-huggingface-token]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = false

[functions.public-api]
verify_jwt = false

[functions.extract-property-data]
verify_jwt = true

[functions.feeds-cnm]
verify_jwt = false

[functions.feeds-olx]
verify_jwt = false

[functions.import-cnm]
verify_jwt = false

[functions.import-vrsync]
verify_jwt = false

[functions.subscription-email-notification]
verify_jwt = false

[functions.subscription-auto-suspend]
verify_jwt = false