-- Create 20 realistic properties for demonstration
INSERT INTO conectaios_properties (
  user_id, titulo, descricao, finalidade, property_type, listing_type, 
  valor, area, quartos, bathrooms, parking_spots, 
  address, neighborhood, city, state, zipcode,
  fotos, is_public, visibility, features, reference_code
) VALUES 

-- Apartamentos de Luxo
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Apartamento de Luxo com Vista Mar',
  'Magnífico apartamento com vista panorâmica para o mar, acabamento de primeira qualidade, móveis planejados e área gourmet completa.',
  'residencial',
  'apartamento',
  'venda',
  850000.00,
  120.5,
  3,
  3,
  2,
  'Avenida Soares Lopes, 150',
  'Pontal',
  'Ilhéus',
  'BA',
  '45653-000',
  ARRAY['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800', 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
  true,
  'public_site',
  '["vista_mar", "mobiliado", "area_gourmet", "piscina", "academia"]'::jsonb,
  'CO00002'
),

-- Casa Moderna
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Casa Moderna no Jardim Atlântico',
  'Casa térrea moderna com 4 suítes, piscina, churrasqueira e jardim amplo. Condomínio fechado com segurança 24h.',
  'residencial',
  'casa',
  'venda',
  1200000.00,
  280.0,
  4,
  5,
  4,
  'Rua das Orquídeas, 45',
  'Jardim Atlântico',
  'Ilhéus',
  'BA',
  '45653-120',
  ARRAY['https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800', 'https://images.unsplash.com/photo-1448630360428-65456885c650?w=800'],
  true,
  'public_site',
  '["piscina", "churrasqueira", "jardim", "condominio_fechado", "portaria_24h"]'::jsonb,
  'CO00003'
),

-- Apartamento Centro
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Apartamento Compacto no Centro',
  'Apartamento bem localizado no centro da cidade, próximo a bancos, comércios e serviços. Ideal para investimento.',
  'residencial',
  'apartamento',
  'venda',
  320000.00,
  65.0,
  2,
  1,
  1,
  'Rua Jorge Amado, 892',
  'Centro',
  'Ilhéus',
  'BA',
  '45653-030',
  ARRAY['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
  true,
  'public_site',
  '["centro", "investimento", "transporte_publico"]'::jsonb,
  'CO00004'
),

-- Sobrado Familiar
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Sobrado Familiar - 3 Pavimentos',
  'Sobrado com 3 pavimentos, 5 quartos sendo 3 suítes, garagem para 3 carros e quintal amplo. Perfeito para famílias grandes.',
  'residencial',
  'sobrado',
  'venda',
  690000.00,
  220.0,
  5,
  4,
  3,
  'Rua do Cajueiro, 78',
  'Cidade Nova',
  'Ilhéus',
  'BA',
  '45653-090',
  ARRAY['https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800', 'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800'],
  true,
  'public_site',
  '["quintal", "garagem_multipla", "familia_grande", "3_pavimentos"]'::jsonb,
  'CO00005'
),

-- Apartamento Aluguel
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Apartamento 2 Quartos para Locação',
  'Apartamento mobilado com 2 quartos, cozinha equipada, área de serviço e sacada. Localização privilegiada.',
  'residencial',
  'apartamento',
  'aluguel',
  2800.00,
  75.0,
  2,
  2,
  1,
  'Avenida Canavieiras, 245',
  'Pontal',
  'Ilhéus',
  'BA',
  '45653-010',
  ARRAY['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
  true,
  'public_site',
  '["mobiliado", "sacada", "cozinha_equipada"]'::jsonb,
  'CO00006'
),

-- Terreno Comercial
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Terreno Comercial - Avenida Principal',
  'Excelente terreno para empreendimento comercial, localizado em avenida de grande movimento. Documentação regularizada.',
  'comercial',
  'terreno',
  'venda',
  450000.00,
  800.0,
  0,
  0,
  0,
  'Avenida Itabuna, s/n',
  'São Francisco',
  'Ilhéus',
  'BA',
  '45653-200',
  ARRAY['https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800'],
  true,
  'public_site',
  '["documentacao_ok", "comercial", "avenida_principal"]'::jsonb,
  'CO00007'
),

-- Casa de Praia
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Casa de Praia - Pé na Areia',
  'Casa rústica com vista para o mar, 4 quartos, varanda ampla e acesso direto à praia. Ideal para temporada.',
  'residencial',
  'casa',
  'venda',
  980000.00,
  180.0,
  4,
  3,
  2,
  'Praia do Sul, 12',
  'Olivença',
  'Ilhéus',
  'BA',
  '45654-000',
  ARRAY['https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800'],
  true,
  'public_site',
  '["vista_mar", "pe_na_areia", "varanda", "rustica"]'::jsonb,
  'CO00008'
),

-- Apartamento Econômico
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Apartamento Econômico - Primeiro Imóvel',
  'Apartamento ideal para quem busca o primeiro imóvel. Localização estratégica com fácil acesso ao transporte público.',
  'residencial',
  'apartamento',
  'venda',
  185000.00,
  48.0,
  2,
  1,
  0,
  'Rua da Esperança, 567',
  'Hernani Sá',
  'Ilhéus',
  'BA',
  '45653-080',
  ARRAY['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'],
  true,
  'public_site',
  '["primeiro_imovel", "economico", "transporte_publico"]'::jsonb,
  'CO00009'
),

-- Sala Comercial
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Sala Comercial - Centro Empresarial',
  'Sala comercial moderna no centro empresarial, com recepção, 2 salas privativas e estacionamento. Pronta para uso.',
  'comercial',
  'comercial',
  'venda',
  280000.00,
  85.0,
  0,
  2,
  2,
  'Av. Lomanto Júnior, 890',
  'Centro',
  'Ilhéus',
  'BA',
  '45653-030',
  ARRAY['https://images.unsplash.com/photo-1497366216548-37526070297c?w=800'],
  true,
  'public_site',
  '["centro_empresarial", "moderna", "estacionamento", "pronta_uso"]'::jsonb,
  'CO00010'
),

-- Casa Condomínio
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Casa em Condomínio Fechado',
  'Casa térrea em condomínio fechado com área de lazer completa. Segurança, piscina, quadra e playground.',
  'residencial',
  'casa',
  'venda',
  540000.00,
  140.0,
  3,
  2,
  2,
  'Condomínio Ville Jardim, Casa 15',
  'Vila Cachoeira',
  'Ilhéus',
  'BA',
  '45653-110',
  ARRAY['https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800'],
  true,
  'public_site',
  '["condominio_fechado", "area_lazer", "seguranca", "playground"]'::jsonb,
  'CO00011'
),

-- Loft Moderno
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Loft Moderno - Conceito Aberto',
  'Loft com conceito aberto, pé-direito alto, mezanino e acabamento contemporâneo. Ideal para jovens profissionais.',
  'residencial',
  'loft',
  'aluguel',
  3200.00,
  90.0,
  1,
  2,
  1,
  'Rua das Palmeiras, 234',
  'Pontal',
  'Ilhéus',
  'BA',
  '45653-010',
  ARRAY['https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800'],
  true,
  'public_site',
  '["loft", "conceito_aberto", "pe_direito_alto", "contemporaneo"]'::jsonb,
  'CO00012'
),

-- Chácara
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Chácara com Pomar e Nascente',
  'Chácara de 2.000m² com casa sede, pomar, nascente de água e ampla área verde. Ideal para descanso e lazer.',
  'residencial',
  'chacara',
  'venda',
  420000.00,
  2000.0,
  3,
  2,
  4,
  'Estrada da Esperança, Km 8',
  'Zona Rural',
  'Ilhéus',
  'BA',
  '45653-970',
  ARRAY['https://images.unsplash.com/photo-1464822759844-d150ad6d1387?w=800'],
  true,
  'public_site',
  '["pomar", "nascente", "area_verde", "zona_rural"]'::jsonb,
  'CO00013'
),

-- Apartamento Cobertura
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Cobertura Duplex - Vista Panorâmica',
  'Cobertura duplex com terraço gourmet, vista panorâmica da cidade e mar. Acabamento premium em todos os ambientes.',
  'residencial',
  'cobertura',
  'venda',
  1450000.00,
  200.0,
  4,
  4,
  3,
  'Edifício Mediterrâneo, Cobertura',
  'Pontal',
  'Ilhéus',
  'BA',
  '45653-010',
  ARRAY['https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?w=800'],
  true,
  'public_site',
  '["cobertura", "duplex", "terraco_gourmet", "vista_panoramica", "premium"]'::jsonb,
  'CO00014'
),

-- Casa Geminada
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Casa Geminada - Ótimo Custo-Benefício',
  'Casa geminada nova com 2 quartos, quintal nos fundos e área de serviço coberta. Excelente custo-benefício.',
  'residencial',
  'casa_geminada',
  'venda',
  235000.00,
  68.0,
  2,
  1,
  1,
  'Rua do Progresso, 445',
  'Nelson Costa',
  'Ilhéus',
  'BA',
  '45653-070',
  ARRAY['https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800'],
  true,
  'public_site',
  '["casa_nova", "quintal", "custo_beneficio"]'::jsonb,
  'CO00015'
),

-- Kitnet Estudantil
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Kitnet Mobiliada - Zona Universitária',
  'Kitnet completamente mobiliada próxima às universidades. Ar-condicionado, internet e todas as comodidades.',
  'residencial',
  'kitnet',
  'aluguel',
  1200.00,
  25.0,
  1,
  1,
  0,
  'Rua Eustáquio Bastos, 78',
  'Centro',
  'Ilhéus',
  'BA',
  '45653-030',
  ARRAY['https://images.unsplash.com/photo-1571624436279-b272adf47d99?w=800'],
  true,
  'public_site',
  '["mobiliada", "universitaria", "ar_condicionado", "internet"]'::jsonb,
  'CO00016'
),

-- Galpão Industrial
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Galpão Industrial - Distrito Empresarial',
  'Galpão industrial com 500m², pé-direito de 8m, escritório administrativo e pátio para manobras.',
  'industrial',
  'galpao',
  'aluguel',
  4800.00,
  500.0,
  0,
  2,
  10,
  'Distrito Industrial, Quadra B',
  'Iguape',
  'Ilhéus',
  'BA',
  '45653-900',
  ARRAY['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800'],
  true,
  'public_site',
  '["industrial", "pe_direito_alto", "patio_manobras", "escritorio"]'::jsonb,
  'CO00017'
),

-- Casa Colonial
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Casa Colonial Histórica - Centro',
  'Casa colonial histórica totalmente restaurada, mantendo características originais. 4 quartos e quintal arborizado.',
  'residencial',
  'casa_colonial',
  'venda',
  650000.00,
  160.0,
  4,
  3,
  2,
  'Rua Coronel Pessoa, 67',
  'Centro Histórico',
  'Ilhéus',
  'BA',
  '45653-030',
  ARRAY['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'],
  true,
  'public_site',
  '["historica", "colonial", "restaurada", "quintal_arborizado"]'::jsonb,
  'CO00018'
),

-- Apartamento Studio
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Studio Moderno - Novo Empreendimento',
  'Studio moderno em novo empreendimento com academia, piscina e espaço gourmet. Entrega em 2025.',
  'residencial',
  'studio',
  'venda',
  195000.00,
  32.0,
  0,
  1,
  1,
  'Residencial Modernité, Torre A',
  'Pontal',
  'Ilhéus',
  'BA',
  '45653-010',
  ARRAY['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
  true,
  'public_site',
  '["lancamento", "moderno", "academia", "piscina", "entrega_2025"]'::jsonb,
  'CO00019'
),

-- Fazenda
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Fazenda Produtiva - Cacau e Gado',
  'Fazenda de 50 hectares com plantação de cacau, pastagem para gado, casa sede e benfeitorias. Rio perene.',
  'rural',
  'fazenda',
  'venda',
  2800000.00,
  500000.0,
  5,
  3,
  0,
  'Zona Rural - Fazenda Boa Vista',
  'Zona Rural',
  'Ilhéus',
  'BA',
  '45653-970',
  ARRAY['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800'],
  true,
  'public_site',
  '["fazenda", "cacau", "gado", "rio", "50_hectares"]'::jsonb,
  'CO00020'
),

-- Pousada
(
  (SELECT user_id FROM profiles WHERE role = 'admin' LIMIT 1),
  'Pousada em Funcionamento - Beira Mar',
  'Pousada com 12 suítes em funcionamento, localizada na beira mar. Ótimo negócio para investimento turístico.',
  'comercial',
  'pousada',
  'venda',
  1650000.00,
  400.0,
  12,
  12,
  8,
  'Praia dos Milionários, s/n',
  'Olivença',
  'Ilhéus',
  'BA',
  '45654-000',
  ARRAY['https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800'],
  true,
  'public_site',
  '["pousada", "funcionamento", "beira_mar", "investimento_turistico", "12_suites"]'::jsonb,
  'CO00021'
);