// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { RUNTIME } from '@/config/runtime';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabaseClient = createClient<Database>(RUNTIME.url, RUNTIME.key, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});

// Export with original name for compatibility
export const supabase = supabaseClient;